import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/71q+QtWvQnL._AC_UX695_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$14000",
    newPrice: "200",
    company: "Nike",
    color: "White",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71r6-JU3kkL._AC_UX695_.jpg",
    title: "Adidas Ultraboost 22",
    star: <AiFillStar className="rating-star" />,
    reviews: "(321 reviews)",
    prevPrice: "$14000",
    newPrice: "180",
    company: "Adidas",
    color: "Black",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71zk5xLgVUL._AC_UX695_.jpg",
    title: "Puma RS-X",
    star: <AiFillStar className="rating-star" />,
    reviews: "(89 reviews)",
    prevPrice: "$14000",
    newPrice: "150",
    company: "Puma",
    color: "Blue",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/71vYv3d2G6L._AC_UX695_.jpg",
    title: "Reebok Nano X2",
    star: <AiFillStar className="rating-star" />,
    reviews: "(207 reviews)",
    prevPrice: "$14000",
    newPrice: "140",
    company: "Reebok",
    color: "Grey",
    category: "training",
  },
  {
    img: "https://m.media-amazon.com/images/I/71J8tz0UeJL._AC_UX695_.jpg",
    title: "Under Armour Charged",
    star: <AiFillStar className="rating-star" />,
    reviews: "(102 reviews)",
    prevPrice: "$14000",
    newPrice: "130",
    company: "Under Armour",
    color: "Red",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/81ZmH7ZEFtL._AC_UX695_.jpg",
    title: "Converse Chuck Taylor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(412 reviews)",
    prevPrice: "$14000",
    newPrice: "90",
    company: "Converse",
    color: "Black",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/81Y0RyvT8kL._AC_UX695_.jpg",
    title: "New Balance 990v5",
    star: <AiFillStar className="rating-star" />,
    reviews: "(295 reviews)",
    prevPrice: "$14000",
    newPrice: "175",
    company: "New Balance",
    color: "Grey",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/61uHZ5VX5dL._AC_UX695_.jpg",
    title: "ASICS Gel-Kayano 28",
    star: <AiFillStar className="rating-star" />,
    reviews: "(159 reviews)",
    prevPrice: "$14000",
    newPrice: "160",
    company: "ASICS",
    color: "White",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71h3XzAcH-L._AC_UX695_.jpg",
    title: "Skechers D'Lites",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "$14000",
    newPrice: "85",
    company: "Skechers",
    color: "Pink",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/61ENMUpM1JL._AC_UX695_.jpg",
    title: "Fila Disruptor II",
    star: <AiFillStar className="rating-star" />,
    reviews: "(231 reviews)",
    prevPrice: "$14000",
    newPrice: "110",
    company: "Fila",
    color: "White",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/51fO2ZFb94L._AC_UX695_.jpg",
    title: "Brooks Ghost 14",
    star: <AiFillStar className="rating-star" />,
    reviews: "(164 reviews)",
    prevPrice: "$14000",
    newPrice: "150",
    company: "Brooks",
    color: "Blue",
    category: "running",
  },
  {
    img: "https://m.media-amazon.com/images/I/71xtEN+gBuL._AC_UX695_.jpg",
    title: "Jordan Air 1 Mid",
    star: <AiFillStar className="rating-star" />,
    reviews: "(398 reviews)",
    prevPrice: "$14000",
    newPrice: "170",
    company: "Jordan",
    color: "Red",
    category: "basketball",
  },
  {
    img: "https://m.media-amazon.com/images/I/61Z9Gz63KnL._AC_UX695_.jpg",
    title: "Timberland Classic Boots",
    star: <AiFillStar className="rating-star" />,
    reviews: "(187 reviews)",
    prevPrice: "$14000",
    newPrice: "200",
    company: "Timberland",
    color: "Tan",
    category: "boots",
  },
  {
    img: "https://m.media-amazon.com/images/I/61bK6KXzDwL._AC_UX695_.jpg",
    title: "Clarks Tilden Cap Oxford",
    star: <AiFillStar className="rating-star" />,
    reviews: "(210 reviews)",
    prevPrice: "$14000",
    newPrice: "95",
    company: "Clarks",
    color: "Brown",
    category: "formal",
  },
  {
    img: "https://m.media-amazon.com/images/I/81NmrY1RrAL._AC_UX695_.jpg",
    title: "Crocs Classic Clog",
    star: <AiFillStar className="rating-star" />,
    reviews: "(503 reviews)",
    prevPrice: "$14000",
    newPrice: "45",
    company: "Crocs",
    color: "Green",
    category: "casual",
  },
  {
    img: "https://m.media-amazon.com/images/I/61YLz9ftJzL._AC_UX695_.jpg",
    title: "Vans Old Skool",
    star: <AiFillStar className="rating-star" />,
    reviews: "(266 reviews)",
    prevPrice: "$14000",
    newPrice: "80",
    company: "Vans",
    color: "Black",
    category: "skate",
  },
  {
    img: "https://m.media-amazon.com/images/I/61TZF9jHleL._AC_UX695_.jpg",
    title: "Birkenstock Arizona",
    star: <AiFillStar className="rating-star" />,
    reviews: "(342 reviews)",
    prevPrice: "$14000",
    newPrice: "120",
    company: "Birkenstock",
    color: "Beige",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/81R2EDs3ZqL._AC_UX695_.jpg",
    title: "Dr. Martens 1460",
    star: <AiFillStar className="rating-star" />,
    reviews: "(172 reviews)",
    prevPrice: "$14000",
    newPrice: "170",
    company: "Dr. Martens",
    color: "Black",
    category: "boots",
  },
  {
    img: "https://m.media-amazon.com/images/I/61kGDXDWpDL._AC_UX695_.jpg",
    title: "Columbia Hiking Boots",
    star: <AiFillStar className="rating-star" />,
    reviews: "(109 reviews)",
    prevPrice: "$14000",
    newPrice: "135",
    company: "Columbia",
    color: "Brown",
    category: "hiking",
  },
  {
    img: "https://m.media-amazon.com/images/I/71Ewzzth+pL._AC_UX695_.jpg",
    title: "Sperry Top-Sider",
    star: <AiFillStar className="rating-star" />,
    reviews: "(193 reviews)",
    prevPrice: "$14000",
    newPrice: "85",
    company: "Sperry",
    color: "Navy",
    category: "boat",
  },
];
